name: Black Box Action
description: Action to retrieve metadata information from repository.
inputs:
  config:
    description: Action configuration in JSON format.
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9.12'
        cache: 'pip'
    - run: pip install -r src/requirements.txt
      shell: bash
    - run: python ${{ github.action_path }}/src/entrypoint.py -c '${{ inputs.config }}'
      shell: bash
